"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
"""


def fibonacci(n):  # recursive function to calculate fibonacci sequence
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)


i = 0
result = 0
while fibonacci(i) < 4000000:  # 4000000 is the limit of the fibonacci sequence
    if fibonacci(i) % 2 == 0:
        result += fibonacci(i)
    i += 1

print(result)  # 4613732
